# Generated by Django 3.0.4 on 2020-05-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('photo_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='usertogroup',
            old_name='group_id',
            new_name='id_group',
        ),
        migrations.RenameField(
            model_name='usertogroup',
            old_name='user_id',
            new_name='id_user',
        ),
        migrations.AddField(
            model_name='expense',
            name='pic_file_path',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='logo_file_path',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
