# Generated by Django 3.0.4 on 2020-05-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_web', '0003_remove_group_logo_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='id_user',
            new_name='id_user_owes',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='split_method',
        ),
        migrations.AddField(
            model_name='expense',
            name='id_user_paid',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(),
        ),
    ]
