# Generated by Django 3.0.4 on 2020-05-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_web', '0004_auto_20200507_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id_group',
            field=models.IntegerField(null=True),
        ),
    ]
